services:
    unipal.mysql.db:
        image: "mysql:latest"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ./config/sql:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"