services:
    amstramgram.mysql.db:
        image: "mysql:latest"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ./config/sql:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
    
    amstramgram.redis.cache:
        image: "redis:7.2.5-alpine"
        restart: always
        command: ["redis-server", "--save", "20", "1", "--loglevel", "warning", "--requirepass", "${REDIS_PASSWORD}"]
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        ports:
            - "6379:6379"